services:
  postgres:
    image: postgres:16-alpine
    container_name: rent_car_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rent_car
    ports:
      - "5432:5432"
    volumes:
      - rent_car_pgdata:/var/lib/postgresql/data

volumes:
  rent_car_pgdata:
